/**
 * Step 3: assemble README.md from the facts, then verify its own invariants.
 * The README is a build artifact; edit the generator, never the output.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { Facts } from "./facts.mts";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

const esc = (s: string) =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

function pic(base: string, alt: string): string {
  return `<picture>
<source media="(max-width: 500px) and (prefers-color-scheme: dark)" srcset="assets/${base}-narrow-dark.svg">
<source media="(max-width: 500px)" srcset="assets/${base}-narrow-light.svg">
<source media="(prefers-color-scheme: dark)" srcset="assets/${base}-dark.svg">
<img alt="${esc(alt)}" src="assets/${base}-light.svg" width="100%">
</picture>`;
}

export function buildReadme(facts: Facts): string {
  const order = facts.order.map((b) => `${b.rank}. ${b.sail} ${b.clock}`).join(" · ");
  const md = `<!-- generated by scripts/readme/build.mts. do not edit by hand. -->

<a href="https://fullbuild.ai/prototype/layline"><img alt="Six racing skiffs at dusk beating toward a mark buoy between two dashed amber laylines, seen from the air" src="assets/img/banner.jpg" width="100%"></a>

${pic("course", `The racecourse drawn from its own seed: six boat tracks beat to the windward mark inside its laylines. Finish order ${facts.order.map((b) => `${b.rank} ${b.sail} ${b.clock}`).join(", ")}.`)}

A browser race replay engine. It takes ${facts.fixHz} position fixes a second per boat, the rate a sailing tracker actually reports, and turns them into continuous 3D motion at display rate: a six boat fleet race you can watch from three camera rigs, scrub, step fix by fix, and read through live instruments and standings.

Everything above this sentence was computed, not illustrated. The tracks, the layline angle, the finish clocks and the fix counts are generated from the same \`generateRace(${facts.seed})\` the app runs, every time the README builds.

**Live demo: [fullbuild.ai/prototype/layline](https://fullbuild.ai/prototype/layline)**

## Run it

\`\`\`bash
npm install
npm run dev
\`\`\`

Open http://localhost:3000. Node 20 or newer. No API keys, no database, no assets to download: the race is generated from seed ${facts.seed} on first render, identically on the server and in your browser.

## What you are looking at

<a href="https://fullbuild.ai/prototype/layline"><img alt="The chase camera at 0:25: four skiffs heeled on the beat with sail numbers readable, live standings on the left and the instrument dock on the right" src="assets/img/chase.png" width="100%"></a>

<table>
<tr>
<td width="62%"><a href="https://fullbuild.ai/prototype/layline"><img alt="The tactical camera with the raw fixes lens on at the mark rounding: each boat trails its actual 4 Hz fix dots, laylines meet at the zone" src="assets/img/raw-tactical.png" width="100%"></a></td>
<td width="38%"><a href="https://fullbuild.ai/prototype/layline"><img alt="The same replay on a phone: chase camera close on one skiff with the HUD reflowed for 390 pixels" src="assets/img/mobile.png" width="100%"></a></td>
</tr>
</table>

- Three camera rigs: a damped chase boat, a TV wide, and a tactical overhead.
- A raw fixes lens that swaps interpolated motion for the actual ${facts.fixHz} Hz readings, so you can see exactly what the engine is working from.
- Frame stepping on the fix grid: the step buttons and the \`,\` \`.\` keys move one 250 ms reading at a time.
- Click any standings row to follow that boat; gaps convert to finish times as boats cross.
- A server rendered SVG chart stands in when WebGL is unavailable, sampled through the same evaluator.

## The problem underneath it

A screen refreshes sixty times a second. Draw only the fixes and each one holds for fifteen frames, then jumps. The boat reaches the mark in the right place at the right time and looks wrong the whole way there.

${pic("hermite", `A real tack from the feed: raw fixes as dots with the cubic Hermite the replay draws through them, and the reported velocity at each fix drawn as an amber tangent arrow.`)}

The replay fills each gap with a cubic Hermite segment whose tangents are the speed and course the boat itself reported at each fix, not differences between neighbors. The curve leaves every fix on the heading that fix recorded and arrives at the next one the same way, so a tack keeps its shape instead of getting its corner rounded off. The panel above is drawn from the feed: a real tack, its real fixes, its real reported velocities.

The rest of the evaluator follows the same rule, believe the instrument, bound it by physics:

- Heading, course and wind angles interpolate the short way around the circle, so 359 to 2 crosses north instead of sweeping the long way through 180.
- Angular tangents are capped at 60 degrees per second, faster than any hull yaws, so one bad fix bends a curve without spinning a boat.
- The gennaker hoist channel is monotone limited, because a plain central difference dips a stowed sail below zero.
- At the ends of a series the pose holds the last fix. Nothing extrapolates into water nobody measured.

One evaluator ([\`src/lib/layline/interpolate.ts\`](src/lib/layline/interpolate.ts)) serves the 3D scene, the instrument dock, the standings and the server chart, so they can only disagree by asking about different times, never by doing different arithmetic.

## Deterministic by construction

Race time is the only clock, advanced only inside a drawn frame. Every visual is a pure function of it: water phase, wakes, trails, spray, course graphics. Scrubbing to a time and playing to it produce identical frames, and wake ribbons re-anchor on whole seconds so the geometry is reproducible byte for byte. One seed builds the race on the server and again in the browser: two readings of one number, never two numbers.

The race itself is simulated at ${facts.simHz} Hz by [\`src/lib/layline/sim.ts\`](src/lib/layline/sim.ts), which never imports three.js: boats that duck and shadow each other, sail headers before tacking, overstand their laylines on purpose, and round wide in, tight out. The sim then throws away everything except what a tracker would have sent: ${facts.fixesTotal} fixes across ${facts.boats} boats and ${facts.feedSeconds} seconds of feed.

## Performance

- The frame path allocates nothing: poses write into caller owned objects, series lookups ride per buffer cursors with bisection only on scrub, the standings reuse one array, and HUD text writes skip the DOM when a reading has not changed.
- The water is a single clipmap mesh, about 26 thousand vertices where a uniform grid at the same detail costs 1.6 million, with ring seams stitched so no cracks open between detail levels.
- The whole fleet draws through one vertex colored material; spray and fix dots are instanced.
- A frame time governor watches the loop and steps the pixel ratio down one rung at a time on sustained misses, so a weak GPU degrades resolution instead of frame rate. It never oscillates back up.

On the desktop GPU this was built against, the scene holds 100 frames per second with a worst frame of 10.2 ms and a clean console.

## Controls

| Input | Action |
| --- | --- |
| Play button, step buttons | Play or pause; step one fix back or forward |
| \`ArrowLeft\` / \`ArrowRight\` on the timeline | Scrub 1 s (with \`Shift\`, 10 s) |
| \`,\` / \`.\` on the timeline | Step one 250 ms fix |
| \`Home\` / \`End\` | Jump to the start or end of the feed |
| 1x / 2x / 4x | Playback rate |
| Raw fixes | Hold each fix instead of interpolating, with the fix strip on the timeline |
| Chase / TV / Tactical | Camera rig |
| Click a standings row | Follow that boat and dock its instruments |

## Tests

\`\`\`bash
npm test
\`\`\`

${facts.testCount} cases pin the parts that must never drift: the seed reproduces the race byte for byte, the evaluator returns every fix exactly at its own time, headings cross the 359/0 seam the short way, sampled turn rate never beats the cap, the kite channel stays inside 0..1, standings resolve the instant a boat's finish time passes, stepping lands on the fix grid, and the display edge never prints \`-0.0\` or a 360 degree bearing.

## Provenance

The race is a fictional event with seeded telemetry; no real boats, teams or venues are depicted. Finish order at seed ${facts.seed}: ${order}. This README is generated by [\`scripts/readme/build.mts\`](scripts/readme/build.mts), which recomputes every number above from the sim and fails the build on any mismatch.

Spec work by Ryan Allen | all demo concepts

## License

[MIT](LICENSE)
`;
  return md;
}

export function verifyReadme(md: string, facts: Facts): string[] {
  const problems: string[] = [];
  if (!md.startsWith("<!-- generated by scripts/readme/build.mts")) {
    problems.push("marker missing from line 1");
  }
  for (const m of md.matchAll(/(?:src|srcset)="(assets\/[^"]+)"/g)) {
    if (!fs.existsSync(path.join(ROOT, m[1]))) problems.push(`missing asset ${m[1]}`);
  }
  const head = md.split("\n").slice(0, 40).join("\n");
  if (!head.includes("npm install")) problems.push("quick start fell below the fold");
  if (!md.includes("https://fullbuild.ai/prototype/layline")) problems.push("live demo link missing");
  for (const value of [String(facts.seed), String(facts.fixesTotal), String(facts.testCount)]) {
    if (!md.includes(value)) problems.push(`fact ${value} missing from prose`);
  }
  return problems;
}
