/**
 * Step 3: assemble README.md from the facts, then verify its own invariants.
 * The README is a build artifact; edit the generator, never the output.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { Facts } from "./facts.mts";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

const esc = (s: string) =>
  String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    /* alt text quotes the question; an unescaped quote ends the attribute. */
    .replace(/"/g, "&quot;");

/* GitHub strips <video> from a README, and its raw host labels a .webm
 * audio/webm, so an embedded player is not available here. The capture ships
 * twice instead: an animated WebP that plays inline in any markdown viewer,
 * linked to the webm itself, which GitHub serves but will not play. */
function clip(base: string, alt: string): string {
  return `<a href="assets/video/${base}.webm"><img alt="${esc(alt)}" src="assets/img/${base}-loop.webp" width="100%"></a>`;
}

function pic(base: string, alt: string): string {
  return `<picture>
<source media="(max-width: 500px) and (prefers-color-scheme: dark)" srcset="assets/${base}-narrow-dark.svg">
<source media="(max-width: 500px)" srcset="assets/${base}-narrow-light.svg">
<source media="(prefers-color-scheme: dark)" srcset="assets/${base}-dark.svg">
<img alt="${esc(alt)}" src="assets/${base}-light.svg" width="100%">
</picture>`;
}

export function buildReadme(facts: Facts): string {
  const md = `<!-- generated by scripts/readme/build.mts. do not edit by hand. -->

<a href="https://fullbuild.ai/prototype/layline"><img alt="Six racing skiffs at dusk heading toward a mark between two amber laylines" src="assets/img/banner.jpg" width="100%"></a>

# Layline

**[Open the live demo](https://fullbuild.ai/prototype/layline)**

Layline replays a six-boat sailing race in the browser. A tracker reports each boat's position ${facts.fixHz} times per second. Layline fills the 250 ms gaps and draws the race at display rate.

You can follow any boat, change cameras, scrub the race, inspect the raw GPS samples, and step through each sample. Debrief answers questions using ${facts.debrief.tools.length} tools that read the same race data.

${pic("course", "Six boat tracks on the generated course with laylines and finish times")}

## Run locally

\`\`\`bash
npm install
npm run dev
\`\`\`

Open http://localhost:3000. Requires Node 20 or newer.

The app needs no database and fetches no race data. It generates the same race on the server and in the browser from seed \`${facts.seed}\`.

Recommended to view on https://fullbuild.ai/prototype/layline

## Replay

<a href="https://fullbuild.ai/prototype/layline"><img alt="The chase camera with standings, boat instruments, playback controls, and timeline" src="assets/img/chase.png" width="100%"></a>

<table>
<tr>
<td width="62%"><a href="https://fullbuild.ai/prototype/layline"><img alt="The tactical camera showing raw GPS samples at 4 Hz" src="assets/img/raw-tactical.png" width="100%"></a></td>
<td width="38%"><a href="https://fullbuild.ai/prototype/layline"><img alt="The replay on a 390 pixel phone" src="assets/img/mobile.png" width="100%"></a></td>
</tr>
</table>

- Chase, TV, tactical, and 2D course views.
- Playback at 1x, 2x, or 4x.
- Scrubbing and 250 ms frame stepping.
- Raw samples mode shows the tracker input without interpolation.
- Clicking a standings row follows that boat and opens its instruments.
- Tack and gybe markers seek to each turn and show the speed lost.
- Start data shows time to the gun, distance to the line, and closing speed.
- Speed made good compares the followed boat with the fleet at the same time.

## How the motion works

A tracker sends 1 GPS point every 250 ms. A 60 Hz screen draws 15 frames during that gap. Holding each sample for all 15 frames makes the boat jump.

${pic("hermite", "Raw GPS samples from a tack with the curve and reported velocity used between them")}

**<ins>[interpolate.ts](src/lib/layline/interpolate.ts)</ins>** fills each gap with a cubic Hermite curve. The boat's reported speed and course set the direction at both ends. The curve passes through every recorded fix while keeping the shape of tacks and roundings.

- Angles take the shortest path around the compass.
- Turn rate is capped at 60 degrees per second.
- The gennaker value stays between 0 and 1.
- Before the first fix and after the last fix, the boat holds position.

The same evaluator supplies the 3D scene, instruments, standings, and 2D course. Every view gets the same result for the same race time.

The simulator runs at ${facts.simHz} Hz, then keeps only the data a ${facts.fixHz} Hz tracker would send. The current seed produces ${facts.fixesTotal.toLocaleString("en-US")} telemetry samples across ${facts.boats} boats and ${facts.feedSeconds} seconds.

## Debrief

${clip("debrief", "Debrief answering a question while the course and evidence update")}

Debrief reads the same \`RaceData\` as the replay. Its ${facts.debrief.tools.length} tools cover standings, boat state, boat comparisons, maneuvers, starts, wind, and sailing terms. Each cited moment becomes a button that seeks the replay and follows the named boat.

${pic("debrief", `The ${facts.debrief.tool} tool returning line position and start time for ${facts.debrief.start.length} boats`)}

Responses stream through server-sent events. Status messages identify each tool call before answer text arrives.

A marker such as \`[[t=32.9|nzl]]\` links an answer to a boat and race time. The client waits for the complete marker before drawing the button.

The route limits requests to the same origin, ${facts.debrief.maxTurns} turns of history, ${facts.debrief.maxChars} characters per message, and four tool rounds. It also rate-limits each app instance. Missing live-model settings return \`503\` and hide Debrief.

## Performance

- Per-frame code reuses pose objects, search cursors, and the standings array.
- Instrument text updates only when a value changes.
- The water uses 27,009 vertices. A uniform grid at the same detail would use 1,640,961.
- The fleet shares 2 hull materials. Spray and raw telemetry dots use instancing.
- Sustained frame misses lower the pixel ratio one step at a time.

## Controls

| Input | Action |
| --- | --- |
| Play and step buttons | Play, pause, or move 1 sample |
| \`ArrowLeft\` / \`ArrowRight\` | Move one second |
| \`Shift\` with arrow keys | Move ten seconds |
| \`,\` / \`.\` | Move one 250 ms fix |
| \`Home\` / \`End\` | Jump to the start or end |
| 1x / 2x / 4x | Set playback speed |
| Raw samples | Show recorded GPS points without interpolation |
| Chase / TV / Tactical | Change camera |
| 2D | Open the course view |
| Maneuver marker | Seek to a tack or gybe |
| Standings row | Follow a boat |
| Debrief moment | Seek to the cited time and boat |

## Tests

\`\`\`bash
npm test
\`\`\`

The ${facts.testCount} tests cover seeded race output, exact samples, interpolation, compass wrapping, turn-rate limits, sail bounds, standings, frame stepping, and display formatting.

Debrief tests cover tool output, maneuver detection, moment markers, glossary lookup, request validation, and mock streaming.

## Data and license

Fictional demo data.

[\`scripts/readme/build.mts\`](scripts/readme/build.mts) generates this README. It recomputes race numbers from the simulator and fails if they no longer match.

[MIT](LICENSE)
`;
  return md;
}

export function verifyReadme(md: string, facts: Facts): string[] {
  const problems: string[] = [];
  if (!md.startsWith("<!-- generated by scripts/readme/build.mts")) {
    problems.push("marker missing from line 1");
  }
  for (const m of md.matchAll(/(?:src|srcset)="(assets\/[^"]+)"/g)) {
    if (!fs.existsSync(path.join(ROOT, m[1]))) problems.push(`missing asset ${m[1]}`);
  }
  const head = md.split("\n").slice(0, 40).join("\n");
  if (!head.includes("npm install")) problems.push("quick start fell below the fold");
  if (!md.includes("https://fullbuild.ai/prototype/layline")) problems.push("live demo link missing");
  for (const value of [
    String(facts.seed),
    facts.fixesTotal.toLocaleString("en-US"),
    String(facts.testCount),
  ]) {
    if (!md.includes(value)) problems.push(`fact ${value} missing from prose`);
  }
  return problems;
}
